// banks\bank4.h generated by generateBank v0.1
// Copyleft 2016 the Mojon Twins

#define ENEMS_1_BANK 4
extern const unsigned char enems_1 [];

#define MAX_ENEMS_TYPE_01_1	10
#define MAX_ENEMS_TYPE_02_1	18
#define MAX_ENEMS_TYPE_03_1	13
#define MAX_ENEMS_TYPE_04_1	4
#define MAX_ENEMS_TYPE_06_1	9
#define HOTSPOTS_1_BANK 4
extern const unsigned char hotspots_1 [];

#define MAX_HOTSPOTS_TYPE_0_1	18
#define MAX_HOTSPOTS_TYPE_1_1	1
#define MAX_HOTSPOTS_TYPE_2_1	5
#define WORK_LEVEL1_TS_PATTERNS1C_BIN_SIZE 2092
#define WORK_LEVEL1_TS_PATTERNS1C_BIN_BANK 4
extern const unsigned char work_level1_ts_patterns1c_bin[2092];

#define WORK_LEVEL1_SS_PATTERNS_ENEMS1C_BIN_SIZE 1207
#define WORK_LEVEL1_SS_PATTERNS_ENEMS1C_BIN_BANK 4
extern const unsigned char work_level1_ss_patterns_enems1c_bin[1207];

#define WORK_LEVEL1_MAP_1C_BIN_SIZE 2788
#define WORK_LEVEL1_MAP_1C_BIN_BANK 4
extern const unsigned char work_level1_map_1c_bin[2788];

#define WORK_LEVEL1_MAP_1_LOCKSC_BIN_SIZE 6
#define WORK_LEVEL1_MAP_1_LOCKSC_BIN_BANK 4
extern const unsigned char work_level1_map_1_locksc_bin[6];

#define WORK_OGT_M_INGAME1_PSG_SIZE 1853
#define WORK_OGT_M_INGAME1_PSG_BANK 4
extern const unsigned char work_ogt_m_ingame1_psg[1853];

#define SS_ENEMS1_00_A_BANK 4
extern const unsigned char ss_enems1_00_a [];

#define SS_ENEMS1_00_B_BANK 4
extern const unsigned char ss_enems1_00_b [];

#define SS_ENEMS1_00_UD_BANK 4
extern const unsigned char ss_enems1_00_ud [];

#define SS_ENEMS1_01_A_BANK 4
extern const unsigned char ss_enems1_01_a [];

#define SS_ENEMS1_01_B_BANK 4
extern const unsigned char ss_enems1_01_b [];

#define SS_ENEMS1_01_UD_BANK 4
extern const unsigned char ss_enems1_01_ud [];

#define SS_ENEMS1_02_A_BANK 4
extern const unsigned char ss_enems1_02_a [];

#define SS_ENEMS1_02_B_BANK 4
extern const unsigned char ss_enems1_02_b [];

#define SS_ENEMS1_02_UD_BANK 4
extern const unsigned char ss_enems1_02_ud [];

#define SS_ENEMS1_03_A_BANK 4
extern const unsigned char ss_enems1_03_a [];

#define SS_ENEMS1_03_B_BANK 4
extern const unsigned char ss_enems1_03_b [];

#define SS_ENEMS1_03_UD_BANK 4
extern const unsigned char ss_enems1_03_ud [];

#define SS_ENEMS1_04_A_BANK 4
extern const unsigned char ss_enems1_04_a [];

#define SS_ENEMS1_04_B_BANK 4
extern const unsigned char ss_enems1_04_b [];

#define SS_ENEMS1_04_UD_BANK 4
extern const unsigned char ss_enems1_04_ud [];

#define SS_ENEMS1_05_A_BANK 4
extern const unsigned char ss_enems1_05_a [];

#define SS_ENEMS1_05_B_BANK 4
extern const unsigned char ss_enems1_05_b [];

#define SS_ENEMS1_05_UD_BANK 4
extern const unsigned char ss_enems1_05_ud [];

#define SS_ENEMS1_06_A_BANK 4
extern const unsigned char ss_enems1_06_a [];

#define SS_ENEMS1_06_B_BANK 4
extern const unsigned char ss_enems1_06_b [];

#define SS_ENEMS1_06_UD_BANK 4
extern const unsigned char ss_enems1_06_ud [];

#define SS_ENEMS1_07_A_BANK 4
extern const unsigned char ss_enems1_07_a [];

#define SS_ENEMS1_07_B_BANK 4
extern const unsigned char ss_enems1_07_b [];

#define SS_ENEMS1_07_UD_BANK 4
extern const unsigned char ss_enems1_07_ud [];

#define TS_META1_TMAPS_BANK 4
extern const unsigned int ts_meta1_tmaps [];

