// banks\bank3.h generated by generateBank v0.1
// Copyleft 2016 the Mojon Twins

#define ENEMS_0_BANK 3
extern const unsigned char enems_0 [];

#define MAX_ENEMS_TYPE_01_0	11
#define MAX_ENEMS_TYPE_02_0	18
#define MAX_ENEMS_TYPE_04_0	5
#define MAX_ENEMS_TYPE_06_0	4
#define MAX_ENEMS_TYPE_09_0	7
#define HOTSPOTS_0_BANK 3
extern const unsigned char hotspots_0 [];

#define MAX_HOTSPOTS_TYPE_0_0	17
#define MAX_HOTSPOTS_TYPE_1_0	2
#define MAX_HOTSPOTS_TYPE_2_0	5
#define WORK_LEVEL0_TS_PATTERNS0C_BIN_SIZE 2076
#define WORK_LEVEL0_TS_PATTERNS0C_BIN_BANK 3
extern const unsigned char work_level0_ts_patterns0c_bin[2076];

#define WORK_LEVEL0_SS_PATTERNS_ENEMS0C_BIN_SIZE 850
#define WORK_LEVEL0_SS_PATTERNS_ENEMS0C_BIN_BANK 3
extern const unsigned char work_level0_ss_patterns_enems0c_bin[850];

#define WORK_LEVEL0_MAP_0C_BIN_SIZE 2477
#define WORK_LEVEL0_MAP_0C_BIN_BANK 3
extern const unsigned char work_level0_map_0c_bin[2477];

#define WORK_LEVEL0_MAP_0_LOCKSC_BIN_SIZE 6
#define WORK_LEVEL0_MAP_0_LOCKSC_BIN_BANK 3
extern const unsigned char work_level0_map_0_locksc_bin[6];

#define WORK_OGT_M_INGAME0_PSG_SIZE 1853
#define WORK_OGT_M_INGAME0_PSG_BANK 3
extern const unsigned char work_ogt_m_ingame0_psg[1853];

#define SS_ENEMS0_00_A_BANK 3
extern const unsigned char ss_enems0_00_a [];

#define SS_ENEMS0_00_B_BANK 3
extern const unsigned char ss_enems0_00_b [];

#define SS_ENEMS0_00_UD_BANK 3
extern const unsigned char ss_enems0_00_ud [];

#define SS_ENEMS0_01_A_BANK 3
extern const unsigned char ss_enems0_01_a [];

#define SS_ENEMS0_01_B_BANK 3
extern const unsigned char ss_enems0_01_b [];

#define SS_ENEMS0_01_UD_BANK 3
extern const unsigned char ss_enems0_01_ud [];

#define SS_ENEMS0_02_A_BANK 3
extern const unsigned char ss_enems0_02_a [];

#define SS_ENEMS0_02_B_BANK 3
extern const unsigned char ss_enems0_02_b [];

#define SS_ENEMS0_02_UD_BANK 3
extern const unsigned char ss_enems0_02_ud [];

#define SS_ENEMS0_03_A_BANK 3
extern const unsigned char ss_enems0_03_a [];

#define SS_ENEMS0_03_B_BANK 3
extern const unsigned char ss_enems0_03_b [];

#define SS_ENEMS0_03_UD_BANK 3
extern const unsigned char ss_enems0_03_ud [];

#define SS_ENEMS0_04_A_BANK 3
extern const unsigned char ss_enems0_04_a [];

#define SS_ENEMS0_04_B_BANK 3
extern const unsigned char ss_enems0_04_b [];

#define SS_ENEMS0_04_UD_BANK 3
extern const unsigned char ss_enems0_04_ud [];

#define SS_ENEMS0_05_A_BANK 3
extern const unsigned char ss_enems0_05_a [];

#define SS_ENEMS0_05_B_BANK 3
extern const unsigned char ss_enems0_05_b [];

#define SS_ENEMS0_05_UD_BANK 3
extern const unsigned char ss_enems0_05_ud [];

#define SS_ENEMS0_06_A_BANK 3
extern const unsigned char ss_enems0_06_a [];

#define SS_ENEMS0_06_B_BANK 3
extern const unsigned char ss_enems0_06_b [];

#define SS_ENEMS0_06_UD_BANK 3
extern const unsigned char ss_enems0_06_ud [];

#define SS_ENEMS0_07_A_BANK 3
extern const unsigned char ss_enems0_07_a [];

#define SS_ENEMS0_07_B_BANK 3
extern const unsigned char ss_enems0_07_b [];

#define SS_ENEMS0_07_UD_BANK 3
extern const unsigned char ss_enems0_07_ud [];

#define TS_META0_TMAPS_BANK 3
extern const unsigned int ts_meta0_tmaps [];

