// banks\bank6.h generated by generateBank v0.1
// Copyleft 2016 the Mojon Twins

#define ENEMS_3_BANK 6
extern const unsigned char enems_3 [];

#define HOTSPOTS_3_BANK 6
extern const unsigned char hotspots_3 [];

#define MAX_HOTSPOTS_TYPE_0_3	12
#define WORK_LEVEL3_TS_PATTERNS3C_BIN_SIZE 2722
#define WORK_LEVEL3_TS_PATTERNS3C_BIN_BANK 6
extern const unsigned char work_level3_ts_patterns3c_bin[2722];

#define WORK_LEVEL3_SS_PATTERNS_ENEMS3C_BIN_SIZE 1147
#define WORK_LEVEL3_SS_PATTERNS_ENEMS3C_BIN_BANK 6
extern const unsigned char work_level3_ss_patterns_enems3c_bin[1147];

#define WORK_LEVEL3_MAP_3C_BIN_SIZE 1381
#define WORK_LEVEL3_MAP_3C_BIN_BANK 6
extern const unsigned char work_level3_map_3c_bin[1381];

#define WORK_LEVEL3_MAP_3_LOCKSC_BIN_SIZE 26
#define WORK_LEVEL3_MAP_3_LOCKSC_BIN_BANK 6
extern const unsigned char work_level3_map_3_locksc_bin[26];

#define WORK_OGT_M_INGAME3_PSG_SIZE 1853
#define WORK_OGT_M_INGAME3_PSG_BANK 6
extern const unsigned char work_ogt_m_ingame3_psg[1853];

#define SS_ENEMS3_00_A_BANK 6
extern const unsigned char ss_enems3_00_a [];

#define SS_ENEMS3_00_B_BANK 6
extern const unsigned char ss_enems3_00_b [];

#define SS_ENEMS3_00_UD_BANK 6
extern const unsigned char ss_enems3_00_ud [];

#define SS_ENEMS3_01_A_BANK 6
extern const unsigned char ss_enems3_01_a [];

#define SS_ENEMS3_01_B_BANK 6
extern const unsigned char ss_enems3_01_b [];

#define SS_ENEMS3_01_UD_BANK 6
extern const unsigned char ss_enems3_01_ud [];

#define SS_ENEMS3_02_A_BANK 6
extern const unsigned char ss_enems3_02_a [];

#define SS_ENEMS3_02_B_BANK 6
extern const unsigned char ss_enems3_02_b [];

#define SS_ENEMS3_02_UD_BANK 6
extern const unsigned char ss_enems3_02_ud [];

#define SS_ENEMS3_03_A_BANK 6
extern const unsigned char ss_enems3_03_a [];

#define SS_ENEMS3_03_B_BANK 6
extern const unsigned char ss_enems3_03_b [];

#define SS_ENEMS3_03_UD_BANK 6
extern const unsigned char ss_enems3_03_ud [];

#define SS_ENEMS3_04_A_BANK 6
extern const unsigned char ss_enems3_04_a [];

#define SS_ENEMS3_04_B_BANK 6
extern const unsigned char ss_enems3_04_b [];

#define SS_ENEMS3_04_UD_BANK 6
extern const unsigned char ss_enems3_04_ud [];

#define SS_ENEMS3_05_A_BANK 6
extern const unsigned char ss_enems3_05_a [];

#define SS_ENEMS3_05_B_BANK 6
extern const unsigned char ss_enems3_05_b [];

#define SS_ENEMS3_05_UD_BANK 6
extern const unsigned char ss_enems3_05_ud [];

#define SS_ENEMS3_06_A_BANK 6
extern const unsigned char ss_enems3_06_a [];

#define SS_ENEMS3_06_B_BANK 6
extern const unsigned char ss_enems3_06_b [];

#define SS_ENEMS3_06_UD_BANK 6
extern const unsigned char ss_enems3_06_ud [];

#define SS_ENEMS3_07_A_BANK 6
extern const unsigned char ss_enems3_07_a [];

#define SS_ENEMS3_07_B_BANK 6
extern const unsigned char ss_enems3_07_b [];

#define SS_ENEMS3_07_UD_BANK 6
extern const unsigned char ss_enems3_07_ud [];

#define TS_META3_TMAPS_BANK 6
extern const unsigned int ts_meta3_tmaps [];

