// banks\bank7.h generated by generateBank v0.1
// Copyleft 2016 the Mojon Twins

#define ENEMS_4_BANK 7
extern const unsigned char enems_4 [];

#define HOTSPOTS_4_BANK 7
extern const unsigned char hotspots_4 [];

#define MAX_HOTSPOTS_TYPE_0_4	17
#define MAX_HOTSPOTS_TYPE_1_4	2
#define MAX_HOTSPOTS_TYPE_2_4	5
#define WORK_LEVEL4_TS_PATTERNS4C_BIN_SIZE 2076
#define WORK_LEVEL4_TS_PATTERNS4C_BIN_BANK 7
extern const unsigned char work_level4_ts_patterns4c_bin[2076];

#define WORK_LEVEL4_SS_PATTERNS_ENEMS4C_BIN_SIZE 1072
#define WORK_LEVEL4_SS_PATTERNS_ENEMS4C_BIN_BANK 7
extern const unsigned char work_level4_ss_patterns_enems4c_bin[1072];

#define WORK_LEVEL4_MAP_4C_BIN_SIZE 2477
#define WORK_LEVEL4_MAP_4C_BIN_BANK 7
extern const unsigned char work_level4_map_4c_bin[2477];

#define WORK_LEVEL4_MAP_4_LOCKSC_BIN_SIZE 6
#define WORK_LEVEL4_MAP_4_LOCKSC_BIN_BANK 7
extern const unsigned char work_level4_map_4_locksc_bin[6];

#define WORK_OGT_M_INGAME4_PSG_SIZE 1853
#define WORK_OGT_M_INGAME4_PSG_BANK 7
extern const unsigned char work_ogt_m_ingame4_psg[1853];

#define SS_ENEMS4_00_A_BANK 7
extern const unsigned char ss_enems4_00_a [];

#define SS_ENEMS4_00_B_BANK 7
extern const unsigned char ss_enems4_00_b [];

#define SS_ENEMS4_00_UD_BANK 7
extern const unsigned char ss_enems4_00_ud [];

#define SS_ENEMS4_01_A_BANK 7
extern const unsigned char ss_enems4_01_a [];

#define SS_ENEMS4_01_B_BANK 7
extern const unsigned char ss_enems4_01_b [];

#define SS_ENEMS4_01_UD_BANK 7
extern const unsigned char ss_enems4_01_ud [];

#define SS_ENEMS4_02_A_BANK 7
extern const unsigned char ss_enems4_02_a [];

#define SS_ENEMS4_02_B_BANK 7
extern const unsigned char ss_enems4_02_b [];

#define SS_ENEMS4_02_UD_BANK 7
extern const unsigned char ss_enems4_02_ud [];

#define SS_ENEMS4_03_A_BANK 7
extern const unsigned char ss_enems4_03_a [];

#define SS_ENEMS4_03_B_BANK 7
extern const unsigned char ss_enems4_03_b [];

#define SS_ENEMS4_03_UD_BANK 7
extern const unsigned char ss_enems4_03_ud [];

#define SS_ENEMS4_04_A_BANK 7
extern const unsigned char ss_enems4_04_a [];

#define SS_ENEMS4_04_B_BANK 7
extern const unsigned char ss_enems4_04_b [];

#define SS_ENEMS4_04_UD_BANK 7
extern const unsigned char ss_enems4_04_ud [];

#define SS_ENEMS4_05_A_BANK 7
extern const unsigned char ss_enems4_05_a [];

#define SS_ENEMS4_05_B_BANK 7
extern const unsigned char ss_enems4_05_b [];

#define SS_ENEMS4_05_UD_BANK 7
extern const unsigned char ss_enems4_05_ud [];

#define SS_ENEMS4_06_A_BANK 7
extern const unsigned char ss_enems4_06_a [];

#define SS_ENEMS4_06_B_BANK 7
extern const unsigned char ss_enems4_06_b [];

#define SS_ENEMS4_06_UD_BANK 7
extern const unsigned char ss_enems4_06_ud [];

#define SS_ENEMS4_07_A_BANK 7
extern const unsigned char ss_enems4_07_a [];

#define SS_ENEMS4_07_B_BANK 7
extern const unsigned char ss_enems4_07_b [];

#define SS_ENEMS4_07_UD_BANK 7
extern const unsigned char ss_enems4_07_ud [];

#define TS_META4_TMAPS_BANK 7
extern const unsigned int ts_meta4_tmaps [];

