// banks\bank5.h generated by generateBank v0.1
// Copyleft 2016 the Mojon Twins

#define ENEMS_2_BANK 5
extern const unsigned char enems_2 [];

#define HOTSPOTS_2_BANK 5
extern const unsigned char hotspots_2 [];

#define MAX_HOTSPOTS_TYPE_0_2	2
#define MAX_HOTSPOTS_TYPE_1_2	3
#define MAX_HOTSPOTS_TYPE_2_2	3
#define MAX_HOTSPOTS_TYPE_3_2	13
#define MAX_HOTSPOTS_TYPE_4_2	3
#define WORK_LEVEL2_TS_PATTERNS2C_BIN_SIZE 2109
#define WORK_LEVEL2_TS_PATTERNS2C_BIN_BANK 5
extern const unsigned char work_level2_ts_patterns2c_bin[2109];

#define WORK_LEVEL2_SS_PATTERNS_ENEMS2C_BIN_SIZE 1072
#define WORK_LEVEL2_SS_PATTERNS_ENEMS2C_BIN_BANK 5
extern const unsigned char work_level2_ss_patterns_enems2c_bin[1072];

#define WORK_LEVEL2_MAP_2C_BIN_SIZE 2301
#define WORK_LEVEL2_MAP_2C_BIN_BANK 5
extern const unsigned char work_level2_map_2c_bin[2301];

#define WORK_LEVEL2_MAP_2_LOCKSC_BIN_SIZE 6
#define WORK_LEVEL2_MAP_2_LOCKSC_BIN_BANK 5
extern const unsigned char work_level2_map_2_locksc_bin[6];

#define WORK_OGT_M_INGAME2_PSG_SIZE 1853
#define WORK_OGT_M_INGAME2_PSG_BANK 5
extern const unsigned char work_ogt_m_ingame2_psg[1853];

#define SS_ENEMS2_00_A_BANK 5
extern const unsigned char ss_enems2_00_a [];

#define SS_ENEMS2_00_B_BANK 5
extern const unsigned char ss_enems2_00_b [];

#define SS_ENEMS2_00_UD_BANK 5
extern const unsigned char ss_enems2_00_ud [];

#define SS_ENEMS2_01_A_BANK 5
extern const unsigned char ss_enems2_01_a [];

#define SS_ENEMS2_01_B_BANK 5
extern const unsigned char ss_enems2_01_b [];

#define SS_ENEMS2_01_UD_BANK 5
extern const unsigned char ss_enems2_01_ud [];

#define SS_ENEMS2_02_A_BANK 5
extern const unsigned char ss_enems2_02_a [];

#define SS_ENEMS2_02_B_BANK 5
extern const unsigned char ss_enems2_02_b [];

#define SS_ENEMS2_02_UD_BANK 5
extern const unsigned char ss_enems2_02_ud [];

#define SS_ENEMS2_03_A_BANK 5
extern const unsigned char ss_enems2_03_a [];

#define SS_ENEMS2_03_B_BANK 5
extern const unsigned char ss_enems2_03_b [];

#define SS_ENEMS2_03_UD_BANK 5
extern const unsigned char ss_enems2_03_ud [];

#define SS_ENEMS2_04_A_BANK 5
extern const unsigned char ss_enems2_04_a [];

#define SS_ENEMS2_04_B_BANK 5
extern const unsigned char ss_enems2_04_b [];

#define SS_ENEMS2_04_UD_BANK 5
extern const unsigned char ss_enems2_04_ud [];

#define SS_ENEMS2_05_A_BANK 5
extern const unsigned char ss_enems2_05_a [];

#define SS_ENEMS2_05_B_BANK 5
extern const unsigned char ss_enems2_05_b [];

#define SS_ENEMS2_05_UD_BANK 5
extern const unsigned char ss_enems2_05_ud [];

#define SS_ENEMS2_06_A_BANK 5
extern const unsigned char ss_enems2_06_a [];

#define SS_ENEMS2_06_B_BANK 5
extern const unsigned char ss_enems2_06_b [];

#define SS_ENEMS2_06_UD_BANK 5
extern const unsigned char ss_enems2_06_ud [];

#define SS_ENEMS2_07_A_BANK 5
extern const unsigned char ss_enems2_07_a [];

#define SS_ENEMS2_07_B_BANK 5
extern const unsigned char ss_enems2_07_b [];

#define SS_ENEMS2_07_UD_BANK 5
extern const unsigned char ss_enems2_07_ud [];

#define TS_META2_TMAPS_BANK 5
extern const unsigned int ts_meta2_tmaps [];

