// Metaspriteset generated by mkts [sms mode]
// Copyleft 2016 The Mojon Twins
 
// Cell #0 cut from (80, 120) to (95, 135)

const unsigned char ss_fixed2_00 [] = {
	0x00, 0x00, 0x02, 0x02,
	0xa9, 0xaa, 
	0xab, 0xac
};
// Software upside down
const unsigned char ss_fixed2_00_ud [] = {
	0x00, 0x00, 0x02, 0x02,
	0xad, 0xae, 
	0xaf, 0xb0
};
// Cell #1 cut from (96, 120) to (111, 135)

const unsigned char ss_fixed2_01 [] = {
	0x00, 0x00, 0x02, 0x02,
	0xb1, 0xb2, 
	0xb3, 0xb4
};
// Software upside down
const unsigned char ss_fixed2_01_ud [] = {
	0x00, 0x00, 0x02, 0x02,
	0xb5, 0xb6, 
	0xb7, 0xb8
};

// 16 patterns used from #169, Next = 185.

